export default {
  LOAD_PAGES: "LOAD_PAGES",
  LOAD_PAGE_BY_ID: "LOAD_PAGE_BY_ID",
  LOAD_PRODUCTS: "LOAD_PRODUCTS",
  LOAD_PRODUCT: "LOAD_PRODUCT",
  LOAD_CONTENT_BY_ID: "LOAD_CONTENT_BY_ID",
  LOAD_CONTENTS_BY_PAGE: "LOAD_CONTENTS_BY_PAGE",
};
